### PR TITLE
Updated to new version and fixed middleware

### PR DESCRIPTION
**Pull request by chemitaxis**
Hi guys, I have updated the code for the new version of MST, and the new package of Middlewares. Thanks.

### CODE REVIEW

**Comment by chemitaxis** [comment]
Hi @eranimo If you want more information about it, here you have the issue in [MST repo](https://github.com/mobxjs/mobx-state-tree/pull/446). This problem is about Create React App. Thanks again ;)

**Review by eranimo — APPROVED** [review]
Thanks for the help! Looks good!

**Comment by chemitaxis** [comment]
Please tell me when the new package is published ;)

**Comment by eranimo** [comment]
@chemitaxis Published version 0.1.2 🎉

**Comment by chemitaxis** [comment]
Thanks!! So fast!!

**Pull request merged**
